version: '3.5'

services:
  app:
    build: ./cbserver
    platform: linux/amd64
    container_name: cbserver
    environment:
      SQLALCHEMY_CONN: postgresql://postgres:password@db:5432/postgres
    ports:
      - "80:80"
    networks:
      - cbanalysis
    restart: unless-stopped
  db:
    container_name: db
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
       - ./pgdata:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - cbanalysis
    restart: unless-stopped

networks:
  cbanalysis:
    name: cbanalysis
    driver: bridge

volumes:
    postgres: