name: cbanalysis
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - geopandas
  - Shapely
  - Rtree
  - pyjanitor
  - click
  - tqdm
  - requests
  - Fiona
  - pylint
  - pytest
  - black
  - pip
  - pip:
    - Janitor
    - pyclean
    - py-dotenv