[tool.poetry]
name = "cb-analysis"
version = "0.1.0"
description = ""
authors = ["Ri Le <r.le@columbia.edu>"]

[tool.poetry.dependencies]
python = "^3.8"
geopandas = "^0.8.1"
pandas = "^1.1.4"
nose = "^1.3.7"
black = "^20.8b1"
requests = "^2.24.0"
pylint = "^2.6.0"
matplotlib = "^3.3.2"
Fiona = "^1.8.17"
GDAL = "^3.1.4"
pyproj = "^2.6.1"
Shapely = "^1.7.1"
Rtree = "^0.9.4"
pyjanitor = "^0.20.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
